# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_7_Login', '0002_auto_20160830_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
