# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_7_Login', '0003_auto_20160830_1418'),
        ('Day_5_Courses', '0002_auto_20160831_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='users',
        ),
        migrations.AddField(
            model_name='courses',
            name='user1',
            field=models.ManyToManyField(related_name='course', to='Day_7_Login.users'),
        ),
    ]
